var searchData=
[
  ['save_5fvaris_2ehpp_7321',['save_varis.hpp',['../d4/d73/save__varis_8hpp.html',1,'']]],
  ['scalar_2ehpp_7322',['scalar.hpp',['../d5/d4c/scalar_8hpp.html',1,'']]],
  ['scalar_5fseq_5fview_2ehpp_7323',['scalar_seq_view.hpp',['../d5/dce/scalar__seq__view_8hpp.html',1,'']]],
  ['scalar_5ftype_2ehpp_7324',['scalar_type.hpp',['../dd/db9/opencl_2scalar__type_8hpp.html',1,'(Global Namespace)'],['../db/dc8/prim_2meta_2scalar__type_8hpp.html',1,'(Global Namespace)']]],
  ['scalar_5ftype_5fpre_2ehpp_7325',['scalar_type_pre.hpp',['../d2/db6/scalar__type__pre_8hpp.html',1,'']]],
  ['scalbn_2ehpp_7326',['scalbn.hpp',['../de/d05/scalbn_8hpp.html',1,'']]],
  ['scale_5fmatrix_5fexp_5fmultiply_2ehpp_7327',['scale_matrix_exp_multiply.hpp',['../d9/df5/scale__matrix__exp__multiply_8hpp.html',1,'']]],
  ['scaled_5fadd_2ehpp_7328',['scaled_add.hpp',['../db/de3/scaled__add_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5fccdf_5flog_2ehpp_7329',['scaled_inv_chi_square_ccdf_log.hpp',['../dd/df8/scaled__inv__chi__square__ccdf__log_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5fcdf_2ehpp_7330',['scaled_inv_chi_square_cdf.hpp',['../d3/da0/scaled__inv__chi__square__cdf_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5fcdf_5flog_2ehpp_7331',['scaled_inv_chi_square_cdf_log.hpp',['../d3/d36/scaled__inv__chi__square__cdf__log_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flccdf_2ehpp_7332',['scaled_inv_chi_square_lccdf.hpp',['../d2/d1d/scaled__inv__chi__square__lccdf_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flcdf_2ehpp_7333',['scaled_inv_chi_square_lcdf.hpp',['../d6/d95/scaled__inv__chi__square__lcdf_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flog_2ehpp_7334',['scaled_inv_chi_square_log.hpp',['../d5/d4d/scaled__inv__chi__square__log_8hpp.html',1,'']]],
  ['scaled_5finv_5fchi_5fsquare_5flpdf_2ehpp_7335',['scaled_inv_chi_square_lpdf.hpp',['../d5/d70/opencl_2prim_2scaled__inv__chi__square__lpdf_8hpp.html',1,'(Global Namespace)'],['../d0/d05/prim_2prob_2scaled__inv__chi__square__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['scaled_5finv_5fchi_5fsquare_5frng_2ehpp_7336',['scaled_inv_chi_square_rng.hpp',['../dd/d6e/scaled__inv__chi__square__rng_8hpp.html',1,'']]],
  ['scoped_5fchainablestack_2ehpp_7337',['scoped_chainablestack.hpp',['../dc/d04/scoped__chainablestack_8hpp.html',1,'']]],
  ['sd_2ehpp_7338',['sd.hpp',['../de/d6a/opencl_2prim_2sd_8hpp.html',1,'(Global Namespace)'],['../d6/d9f/opencl_2rev_2sd_8hpp.html',1,'(Global Namespace)'],['../d3/dc2/prim_2fun_2sd_8hpp.html',1,'(Global Namespace)'],['../df/d50/rev_2fun_2sd_8hpp.html',1,'(Global Namespace)']]],
  ['segment_2ehpp_7339',['segment.hpp',['../d3/d96/opencl_2prim_2segment_8hpp.html',1,'(Global Namespace)'],['../d9/d6c/prim_2fun_2segment_8hpp.html',1,'(Global Namespace)']]],
  ['select_2ehpp_7340',['select.hpp',['../d2/d84/select_8hpp.html',1,'']]],
  ['seq_5fview_2ehpp_7341',['seq_view.hpp',['../d9/ddc/seq__view_8hpp.html',1,'']]],
  ['set_5fzero_5fall_5fadjoints_2ehpp_7342',['set_zero_all_adjoints.hpp',['../d5/d6c/set__zero__all__adjoints_8hpp.html',1,'']]],
  ['set_5fzero_5fall_5fadjoints_5fnested_2ehpp_7343',['set_zero_all_adjoints_nested.hpp',['../dc/d56/set__zero__all__adjoints__nested_8hpp.html',1,'']]],
  ['sign_2ehpp_7344',['sign.hpp',['../d3/db1/opencl_2prim_2sign_8hpp.html',1,'(Global Namespace)'],['../de/d00/prim_2fun_2sign_8hpp.html',1,'(Global Namespace)']]],
  ['signbit_2ehpp_7345',['signbit.hpp',['../dc/d44/signbit_8hpp.html',1,'']]],
  ['simplex_5fconstrain_2ehpp_7346',['simplex_constrain.hpp',['../d5/d73/prim_2fun_2simplex__constrain_8hpp.html',1,'(Global Namespace)'],['../d7/d75/rev_2fun_2simplex__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['simplex_5ffree_2ehpp_7347',['simplex_free.hpp',['../d8/d3f/simplex__free_8hpp.html',1,'']]],
  ['sin_2ehpp_7348',['sin.hpp',['../dd/df5/fwd_2fun_2sin_8hpp.html',1,'(Global Namespace)'],['../d5/d29/opencl_2rev_2sin_8hpp.html',1,'(Global Namespace)'],['../d3/d9e/prim_2fun_2sin_8hpp.html',1,'(Global Namespace)'],['../d4/de3/rev_2fun_2sin_8hpp.html',1,'(Global Namespace)']]],
  ['singular_5fvalues_2ehpp_7349',['singular_values.hpp',['../d1/d5b/prim_2fun_2singular__values_8hpp.html',1,'(Global Namespace)'],['../db/d9a/rev_2fun_2singular__values_8hpp.html',1,'(Global Namespace)']]],
  ['sinh_2ehpp_7350',['sinh.hpp',['../d9/d28/fwd_2fun_2sinh_8hpp.html',1,'(Global Namespace)'],['../de/dd3/opencl_2rev_2sinh_8hpp.html',1,'(Global Namespace)'],['../d3/d01/prim_2fun_2sinh_8hpp.html',1,'(Global Namespace)'],['../d3/d2b/rev_2fun_2sinh_8hpp.html',1,'(Global Namespace)']]],
  ['size_2ehpp_7351',['size.hpp',['../de/df3/opencl_2prim_2size_8hpp.html',1,'(Global Namespace)'],['../d9/d1c/prim_2fun_2size_8hpp.html',1,'(Global Namespace)']]],
  ['size_5fmvt_2ehpp_7352',['size_mvt.hpp',['../d2/da6/size__mvt_8hpp.html',1,'']]],
  ['size_5fzero_2ehpp_7353',['size_zero.hpp',['../da/d9e/size__zero_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5fccdf_5flog_2ehpp_7354',['skew_double_exponential_ccdf_log.hpp',['../d3/d36/skew__double__exponential__ccdf__log_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5fcdf_2ehpp_7355',['skew_double_exponential_cdf.hpp',['../de/dba/opencl_2prim_2skew__double__exponential__cdf_8hpp.html',1,'(Global Namespace)'],['../d3/d6f/prim_2prob_2skew__double__exponential__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5fcdf_5flog_2ehpp_7356',['skew_double_exponential_cdf_log.hpp',['../d9/da0/skew__double__exponential__cdf__log_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5flccdf_2ehpp_7357',['skew_double_exponential_lccdf.hpp',['../d8/d40/opencl_2prim_2skew__double__exponential__lccdf_8hpp.html',1,'(Global Namespace)'],['../d1/db6/prim_2prob_2skew__double__exponential__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5flcdf_2ehpp_7358',['skew_double_exponential_lcdf.hpp',['../d7/d4f/opencl_2prim_2skew__double__exponential__lcdf_8hpp.html',1,'(Global Namespace)'],['../d2/dcd/prim_2prob_2skew__double__exponential__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5flog_2ehpp_7359',['skew_double_exponential_log.hpp',['../d5/d9c/skew__double__exponential__log_8hpp.html',1,'']]],
  ['skew_5fdouble_5fexponential_5flpdf_2ehpp_7360',['skew_double_exponential_lpdf.hpp',['../db/d1f/opencl_2prim_2skew__double__exponential__lpdf_8hpp.html',1,'(Global Namespace)'],['../d8/d19/prim_2prob_2skew__double__exponential__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fdouble_5fexponential_5frng_2ehpp_7361',['skew_double_exponential_rng.hpp',['../d3/df2/skew__double__exponential__rng_8hpp.html',1,'']]],
  ['skew_5fnormal_5fccdf_5flog_2ehpp_7362',['skew_normal_ccdf_log.hpp',['../d0/d6e/skew__normal__ccdf__log_8hpp.html',1,'']]],
  ['skew_5fnormal_5fcdf_2ehpp_7363',['skew_normal_cdf.hpp',['../d8/dd6/skew__normal__cdf_8hpp.html',1,'']]],
  ['skew_5fnormal_5fcdf_5flog_2ehpp_7364',['skew_normal_cdf_log.hpp',['../d3/da1/skew__normal__cdf__log_8hpp.html',1,'']]],
  ['skew_5fnormal_5flccdf_2ehpp_7365',['skew_normal_lccdf.hpp',['../dd/d28/skew__normal__lccdf_8hpp.html',1,'']]],
  ['skew_5fnormal_5flcdf_2ehpp_7366',['skew_normal_lcdf.hpp',['../de/d49/skew__normal__lcdf_8hpp.html',1,'']]],
  ['skew_5fnormal_5flog_2ehpp_7367',['skew_normal_log.hpp',['../d7/d72/skew__normal__log_8hpp.html',1,'']]],
  ['skew_5fnormal_5flpdf_2ehpp_7368',['skew_normal_lpdf.hpp',['../d7/dfa/opencl_2prim_2skew__normal__lpdf_8hpp.html',1,'(Global Namespace)'],['../d4/da1/prim_2prob_2skew__normal__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['skew_5fnormal_5frng_2ehpp_7369',['skew_normal_rng.hpp',['../df/ddc/skew__normal__rng_8hpp.html',1,'']]],
  ['softmax_2ehpp_7370',['softmax.hpp',['../d9/d45/fwd_2fun_2softmax_8hpp.html',1,'(Global Namespace)'],['../db/d65/opencl_2prim_2softmax_8hpp.html',1,'(Global Namespace)'],['../df/d7a/opencl_2rev_2softmax_8hpp.html',1,'(Global Namespace)'],['../d9/dba/prim_2fun_2softmax_8hpp.html',1,'(Global Namespace)'],['../df/dfe/rev_2fun_2softmax_8hpp.html',1,'(Global Namespace)']]],
  ['sort_5fasc_2ehpp_7371',['sort_asc.hpp',['../d1/da3/opencl_2prim_2sort__asc_8hpp.html',1,'(Global Namespace)'],['../d9/d51/prim_2fun_2sort__asc_8hpp.html',1,'(Global Namespace)']]],
  ['sort_5fdesc_2ehpp_7372',['sort_desc.hpp',['../d7/d4d/opencl_2prim_2sort__desc_8hpp.html',1,'(Global Namespace)'],['../d0/d39/prim_2fun_2sort__desc_8hpp.html',1,'(Global Namespace)']]],
  ['sort_5findices_2ehpp_7373',['sort_indices.hpp',['../d8/d13/sort__indices_8hpp.html',1,'']]],
  ['sort_5findices_5fasc_2ehpp_7374',['sort_indices_asc.hpp',['../d9/de6/sort__indices__asc_8hpp.html',1,'']]],
  ['sort_5findices_5fdesc_2ehpp_7375',['sort_indices_desc.hpp',['../d7/d38/sort__indices__desc_8hpp.html',1,'']]],
  ['sqrt_2ehpp_7376',['sqrt.hpp',['../d0/dd0/fwd_2fun_2sqrt_8hpp.html',1,'(Global Namespace)'],['../d5/d32/opencl_2rev_2sqrt_8hpp.html',1,'(Global Namespace)'],['../d9/d18/prim_2fun_2sqrt_8hpp.html',1,'(Global Namespace)'],['../d6/d50/rev_2fun_2sqrt_8hpp.html',1,'(Global Namespace)']]],
  ['square_2ehpp_7377',['square.hpp',['../d0/d28/fwd_2fun_2square_8hpp.html',1,'(Global Namespace)'],['../de/d45/opencl_2rev_2square_8hpp.html',1,'(Global Namespace)'],['../dd/d56/prim_2fun_2square_8hpp.html',1,'(Global Namespace)'],['../d2/d10/rev_2fun_2square_8hpp.html',1,'(Global Namespace)']]],
  ['squared_5fdistance_2ehpp_7378',['squared_distance.hpp',['../d4/d46/opencl_2prim_2squared__distance_8hpp.html',1,'(Global Namespace)'],['../dd/dc0/opencl_2rev_2squared__distance_8hpp.html',1,'(Global Namespace)'],['../d3/d5a/prim_2fun_2squared__distance_8hpp.html',1,'(Global Namespace)'],['../d6/db7/rev_2fun_2squared__distance_8hpp.html',1,'(Global Namespace)']]],
  ['stack_5falloc_2ehpp_7379',['stack_alloc.hpp',['../d2/dbd/stack__alloc_8hpp.html',1,'']]],
  ['stan_2edox_7380',['stan.dox',['../da/da5/stan_8dox.html',1,'']]],
  ['stan_5fprint_2ehpp_7381',['stan_print.hpp',['../da/d16/prim_2fun_2stan__print_8hpp.html',1,'(Global Namespace)'],['../da/dbc/rev_2fun_2stan__print_8hpp.html',1,'(Global Namespace)']]],
  ['start_5fnested_2ehpp_7382',['start_nested.hpp',['../d4/d05/start__nested_8hpp.html',1,'']]],
  ['static_5fselect_2ehpp_7383',['static_select.hpp',['../dc/d94/static__select_8hpp.html',1,'']]],
  ['std_5fcomplex_2ehpp_7384',['std_complex.hpp',['../dd/d9e/fwd_2core_2std__complex_8hpp.html',1,'(Global Namespace)'],['../d3/dc2/rev_2core_2std__complex_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fisinf_2ehpp_7385',['std_isinf.hpp',['../d5/dea/std__isinf_8hpp.html',1,'']]],
  ['std_5fisnan_2ehpp_7386',['std_isnan.hpp',['../da/d57/std__isnan_8hpp.html',1,'']]],
  ['std_5fiterator_5ftraits_2ehpp_7387',['std_iterator_traits.hpp',['../d7/d32/fwd_2core_2std__iterator__traits_8hpp.html',1,'(Global Namespace)'],['../df/ddd/rev_2core_2std__iterator__traits_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5fccdf_5flog_2ehpp_7388',['std_normal_ccdf_log.hpp',['../d7/d23/std__normal__ccdf__log_8hpp.html',1,'']]],
  ['std_5fnormal_5fcdf_2ehpp_7389',['std_normal_cdf.hpp',['../d1/dd3/opencl_2prim_2std__normal__cdf_8hpp.html',1,'(Global Namespace)'],['../d6/d71/prim_2prob_2std__normal__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5fcdf_5flog_2ehpp_7390',['std_normal_cdf_log.hpp',['../d1/d92/std__normal__cdf__log_8hpp.html',1,'']]],
  ['std_5fnormal_5flccdf_2ehpp_7391',['std_normal_lccdf.hpp',['../db/df5/opencl_2prim_2std__normal__lccdf_8hpp.html',1,'(Global Namespace)'],['../d3/dae/prim_2prob_2std__normal__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5flcdf_2ehpp_7392',['std_normal_lcdf.hpp',['../d1/d46/opencl_2prim_2std__normal__lcdf_8hpp.html',1,'(Global Namespace)'],['../d7/dba/prim_2prob_2std__normal__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5flog_2ehpp_7393',['std_normal_log.hpp',['../d6/df6/std__normal__log_8hpp.html',1,'']]],
  ['std_5fnormal_5flog_5fqf_2ehpp_7394',['std_normal_log_qf.hpp',['../d4/d13/fwd_2prob_2std__normal__log__qf_8hpp.html',1,'(Global Namespace)'],['../d1/d00/prim_2prob_2std__normal__log__qf_8hpp.html',1,'(Global Namespace)'],['../d7/d2c/rev_2prob_2std__normal__log__qf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5flpdf_2ehpp_7395',['std_normal_lpdf.hpp',['../d2/d83/opencl_2prim_2std__normal__lpdf_8hpp.html',1,'(Global Namespace)'],['../d2/d01/prim_2prob_2std__normal__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['std_5fnormal_5frng_2ehpp_7396',['std_normal_rng.hpp',['../d4/dcc/std__normal__rng_8hpp.html',1,'']]],
  ['std_5fnumeric_5flimits_2ehpp_7397',['std_numeric_limits.hpp',['../dc/dec/fwd_2core_2std__numeric__limits_8hpp.html',1,'(Global Namespace)'],['../d5/ddc/rev_2core_2std__numeric__limits_8hpp.html',1,'(Global Namespace)']]],
  ['stdvectorbuilder_2ehpp_7398',['StdVectorBuilder.hpp',['../df/d14/_std_vector_builder_8hpp.html',1,'']]],
  ['step_2ehpp_7399',['step.hpp',['../d9/d93/prim_2fun_2step_8hpp.html',1,'(Global Namespace)'],['../dc/d76/rev_2fun_2step_8hpp.html',1,'(Global Namespace)']]],
  ['stored_5fgradient_5fvari_2ehpp_7400',['stored_gradient_vari.hpp',['../d3/de5/stored__gradient__vari_8hpp.html',1,'']]],
  ['stringify_2ehpp_7401',['stringify.hpp',['../d6/d9f/stringify_8hpp.html',1,'']]],
  ['student_5ft_5fccdf_5flog_2ehpp_7402',['student_t_ccdf_log.hpp',['../d5/d0a/student__t__ccdf__log_8hpp.html',1,'']]],
  ['student_5ft_5fcdf_2ehpp_7403',['student_t_cdf.hpp',['../d5/d66/student__t__cdf_8hpp.html',1,'']]],
  ['student_5ft_5fcdf_5flog_2ehpp_7404',['student_t_cdf_log.hpp',['../d3/d30/student__t__cdf__log_8hpp.html',1,'']]],
  ['student_5ft_5flccdf_2ehpp_7405',['student_t_lccdf.hpp',['../d5/ded/student__t__lccdf_8hpp.html',1,'']]],
  ['student_5ft_5flcdf_2ehpp_7406',['student_t_lcdf.hpp',['../d5/d96/student__t__lcdf_8hpp.html',1,'']]],
  ['student_5ft_5flog_2ehpp_7407',['student_t_log.hpp',['../d7/d8c/student__t__log_8hpp.html',1,'']]],
  ['student_5ft_5flpdf_2ehpp_7408',['student_t_lpdf.hpp',['../d4/d73/opencl_2prim_2student__t__lpdf_8hpp.html',1,'(Global Namespace)'],['../d1/da3/prim_2prob_2student__t__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['student_5ft_5frng_2ehpp_7409',['student_t_rng.hpp',['../dc/d54/student__t__rng_8hpp.html',1,'']]],
  ['sub_5fcol_2ehpp_7410',['sub_col.hpp',['../df/da4/opencl_2prim_2sub__col_8hpp.html',1,'(Global Namespace)'],['../dc/da7/prim_2fun_2sub__col_8hpp.html',1,'(Global Namespace)']]],
  ['sub_5frow_2ehpp_7411',['sub_row.hpp',['../d7/d6d/opencl_2prim_2sub__row_8hpp.html',1,'(Global Namespace)'],['../dd/d77/prim_2fun_2sub__row_8hpp.html',1,'(Global Namespace)']]],
  ['subtract_2ehpp_7412',['subtract.hpp',['../d2/d75/opencl_2rev_2subtract_8hpp.html',1,'(Global Namespace)'],['../d7/d1d/prim_2fun_2subtract_8hpp.html',1,'(Global Namespace)']]],
  ['sum_2ehpp_7413',['sum.hpp',['../d3/df6/fwd_2fun_2sum_8hpp.html',1,'(Global Namespace)'],['../df/d3e/opencl_2prim_2sum_8hpp.html',1,'(Global Namespace)'],['../d5/d98/opencl_2rev_2sum_8hpp.html',1,'(Global Namespace)'],['../dd/d87/prim_2fun_2sum_8hpp.html',1,'(Global Namespace)'],['../d6/d35/rev_2fun_2sum_8hpp.html',1,'(Global Namespace)']]],
  ['svd_5fu_2ehpp_7414',['svd_U.hpp',['../dd/dbf/prim_2fun_2svd___u_8hpp.html',1,'(Global Namespace)'],['../dd/d6c/rev_2fun_2svd___u_8hpp.html',1,'(Global Namespace)']]],
  ['svd_5fv_2ehpp_7415',['svd_V.hpp',['../dd/d17/prim_2fun_2svd___v_8hpp.html',1,'(Global Namespace)'],['../d5/d08/rev_2fun_2svd___v_8hpp.html',1,'(Global Namespace)']]],
  ['symmetric_5feigensolver_2ehpp_7416',['symmetric_eigensolver.hpp',['../d7/d4f/symmetric__eigensolver_8hpp.html',1,'']]],
  ['symmetrize_5ffrom_5flower_5ftri_2ehpp_7417',['symmetrize_from_lower_tri.hpp',['../da/dc1/opencl_2prim_2symmetrize__from__lower__tri_8hpp.html',1,'(Global Namespace)'],['../d4/d52/opencl_2rev_2symmetrize__from__lower__tri_8hpp.html',1,'(Global Namespace)'],['../de/d09/prim_2fun_2symmetrize__from__lower__tri_8hpp.html',1,'(Global Namespace)']]],
  ['symmetrize_5ffrom_5fupper_5ftri_2ehpp_7418',['symmetrize_from_upper_tri.hpp',['../d1/d94/opencl_2prim_2symmetrize__from__upper__tri_8hpp.html',1,'(Global Namespace)'],['../d3/d67/opencl_2rev_2symmetrize__from__upper__tri_8hpp.html',1,'(Global Namespace)'],['../de/d77/prim_2fun_2symmetrize__from__upper__tri_8hpp.html',1,'(Global Namespace)']]],
  ['system_5ferror_2ehpp_7419',['system_error.hpp',['../d6/d80/system__error_8hpp.html',1,'']]]
];
