var searchData=
[
  ['pack_2ehpp_7194',['pack.hpp',['../d3/d83/pack_8hpp.html',1,'']]],
  ['pareto_5fccdf_5flog_2ehpp_7195',['pareto_ccdf_log.hpp',['../d5/d59/pareto__ccdf__log_8hpp.html',1,'']]],
  ['pareto_5fcdf_2ehpp_7196',['pareto_cdf.hpp',['../d5/d11/opencl_2prim_2pareto__cdf_8hpp.html',1,'(Global Namespace)'],['../d3/d63/prim_2prob_2pareto__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5fcdf_5flog_2ehpp_7197',['pareto_cdf_log.hpp',['../d4/dff/pareto__cdf__log_8hpp.html',1,'']]],
  ['pareto_5flccdf_2ehpp_7198',['pareto_lccdf.hpp',['../d4/dd8/opencl_2prim_2pareto__lccdf_8hpp.html',1,'(Global Namespace)'],['../d0/ddd/prim_2prob_2pareto__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5flcdf_2ehpp_7199',['pareto_lcdf.hpp',['../d2/da5/opencl_2prim_2pareto__lcdf_8hpp.html',1,'(Global Namespace)'],['../d3/d4f/prim_2prob_2pareto__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5flog_2ehpp_7200',['pareto_log.hpp',['../da/d9c/pareto__log_8hpp.html',1,'']]],
  ['pareto_5flpdf_2ehpp_7201',['pareto_lpdf.hpp',['../dd/d28/opencl_2prim_2pareto__lpdf_8hpp.html',1,'(Global Namespace)'],['../db/d15/prim_2prob_2pareto__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5frng_2ehpp_7202',['pareto_rng.hpp',['../d3/dfe/pareto__rng_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5fccdf_5flog_2ehpp_7203',['pareto_type_2_ccdf_log.hpp',['../db/da8/pareto__type__2__ccdf__log_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5fcdf_2ehpp_7204',['pareto_type_2_cdf.hpp',['../da/dd9/opencl_2prim_2pareto__type__2__cdf_8hpp.html',1,'(Global Namespace)'],['../dc/dba/prim_2prob_2pareto__type__2__cdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5fcdf_5flog_2ehpp_7205',['pareto_type_2_cdf_log.hpp',['../d5/d59/pareto__type__2__cdf__log_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5flccdf_2ehpp_7206',['pareto_type_2_lccdf.hpp',['../dd/d46/opencl_2prim_2pareto__type__2__lccdf_8hpp.html',1,'(Global Namespace)'],['../dd/dfc/prim_2prob_2pareto__type__2__lccdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5flcdf_2ehpp_7207',['pareto_type_2_lcdf.hpp',['../da/dbe/opencl_2prim_2pareto__type__2__lcdf_8hpp.html',1,'(Global Namespace)'],['../db/db0/prim_2prob_2pareto__type__2__lcdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5flog_2ehpp_7208',['pareto_type_2_log.hpp',['../d3/dee/pareto__type__2__log_8hpp.html',1,'']]],
  ['pareto_5ftype_5f2_5flpdf_2ehpp_7209',['pareto_type_2_lpdf.hpp',['../da/da0/opencl_2prim_2pareto__type__2__lpdf_8hpp.html',1,'(Global Namespace)'],['../db/dfe/prim_2prob_2pareto__type__2__lpdf_8hpp.html',1,'(Global Namespace)']]],
  ['pareto_5ftype_5f2_5frng_2ehpp_7210',['pareto_type_2_rng.hpp',['../dd/d26/pareto__type__2__rng_8hpp.html',1,'']]],
  ['partial_5fderivative_2ehpp_7211',['partial_derivative.hpp',['../d4/de6/partial__derivative_8hpp.html',1,'']]],
  ['partials_5freturn_5ftype_2ehpp_7212',['partials_return_type.hpp',['../df/d23/partials__return__type_8hpp.html',1,'']]],
  ['partials_5ftype_2ehpp_7213',['partials_type.hpp',['../dc/dfb/fwd_2meta_2partials__type_8hpp.html',1,'(Global Namespace)'],['../dd/d43/prim_2meta_2partials__type_8hpp.html',1,'(Global Namespace)'],['../df/d86/rev_2meta_2partials__type_8hpp.html',1,'(Global Namespace)']]],
  ['phi_2ehpp_7214',['Phi.hpp',['../db/dab/fwd_2fun_2_phi_8hpp.html',1,'(Global Namespace)'],['../df/d74/opencl_2kernels_2device__functions_2_phi_8hpp.html',1,'(Global Namespace)'],['../d3/d25/opencl_2rev_2_phi_8hpp.html',1,'(Global Namespace)'],['../de/d40/prim_2fun_2_phi_8hpp.html',1,'(Global Namespace)'],['../da/d80/rev_2fun_2_phi_8hpp.html',1,'(Global Namespace)']]],
  ['phi_5fapprox_2ehpp_7215',['Phi_approx.hpp',['../da/d07/fwd_2fun_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../d6/d14/opencl_2kernels_2device__functions_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../d4/dbb/opencl_2rev_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../d5/d43/prim_2fun_2_phi__approx_8hpp.html',1,'(Global Namespace)'],['../d7/d85/rev_2fun_2_phi__approx_8hpp.html',1,'(Global Namespace)']]],
  ['pinned_5fmatrix_2ehpp_7216',['pinned_matrix.hpp',['../d6/d58/pinned__matrix_8hpp.html',1,'']]],
  ['plain_5ftype_2ehpp_7217',['plain_type.hpp',['../df/dc2/opencl_2plain__type_8hpp.html',1,'(Global Namespace)'],['../db/d84/prim_2meta_2plain__type_8hpp.html',1,'(Global Namespace)'],['../d6/d96/rev_2meta_2plain__type_8hpp.html',1,'(Global Namespace)']]],
  ['plus_2ehpp_7218',['plus.hpp',['../d5/d33/plus_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5fccdf_5flog_2ehpp_7219',['poisson_binomial_ccdf_log.hpp',['../db/d52/poisson__binomial__ccdf__log_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5fcdf_2ehpp_7220',['poisson_binomial_cdf.hpp',['../df/dde/poisson__binomial__cdf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5fcdf_5flog_2ehpp_7221',['poisson_binomial_cdf_log.hpp',['../d3/d96/poisson__binomial__cdf__log_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flccdf_2ehpp_7222',['poisson_binomial_lccdf.hpp',['../d7/d18/poisson__binomial__lccdf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flcdf_2ehpp_7223',['poisson_binomial_lcdf.hpp',['../db/de9/poisson__binomial__lcdf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flog_2ehpp_7224',['poisson_binomial_log.hpp',['../db/dfb/poisson__binomial__log_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flog_5fprobs_2ehpp_7225',['poisson_binomial_log_probs.hpp',['../d2/d1a/poisson__binomial__log__probs_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5flpmf_2ehpp_7226',['poisson_binomial_lpmf.hpp',['../d0/dc5/poisson__binomial__lpmf_8hpp.html',1,'']]],
  ['poisson_5fbinomial_5frng_2ehpp_7227',['poisson_binomial_rng.hpp',['../d0/d73/poisson__binomial__rng_8hpp.html',1,'']]],
  ['poisson_5fccdf_5flog_2ehpp_7228',['poisson_ccdf_log.hpp',['../d2/d2d/poisson__ccdf__log_8hpp.html',1,'']]],
  ['poisson_5fcdf_2ehpp_7229',['poisson_cdf.hpp',['../d7/da5/poisson__cdf_8hpp.html',1,'']]],
  ['poisson_5fcdf_5flog_2ehpp_7230',['poisson_cdf_log.hpp',['../d8/dba/poisson__cdf__log_8hpp.html',1,'']]],
  ['poisson_5flccdf_2ehpp_7231',['poisson_lccdf.hpp',['../d9/dff/poisson__lccdf_8hpp.html',1,'']]],
  ['poisson_5flcdf_2ehpp_7232',['poisson_lcdf.hpp',['../db/d9d/poisson__lcdf_8hpp.html',1,'']]],
  ['poisson_5flog_2ehpp_7233',['poisson_log.hpp',['../d3/ddb/poisson__log_8hpp.html',1,'']]],
  ['poisson_5flog_5fglm_5flog_2ehpp_7234',['poisson_log_glm_log.hpp',['../d4/d8d/poisson__log__glm__log_8hpp.html',1,'']]],
  ['poisson_5flog_5fglm_5flpmf_2ehpp_7235',['poisson_log_glm_lpmf.hpp',['../dc/dbf/opencl_2prim_2poisson__log__glm__lpmf_8hpp.html',1,'(Global Namespace)'],['../d3/dd2/prim_2prob_2poisson__log__glm__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['poisson_5flog_5flog_2ehpp_7236',['poisson_log_log.hpp',['../db/dc0/poisson__log__log_8hpp.html',1,'']]],
  ['poisson_5flog_5flpmf_2ehpp_7237',['poisson_log_lpmf.hpp',['../d7/d28/opencl_2prim_2poisson__log__lpmf_8hpp.html',1,'(Global Namespace)'],['../d4/d2a/prim_2prob_2poisson__log__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['poisson_5flog_5frng_2ehpp_7238',['poisson_log_rng.hpp',['../d9/da1/poisson__log__rng_8hpp.html',1,'']]],
  ['poisson_5flpmf_2ehpp_7239',['poisson_lpmf.hpp',['../d8/df5/opencl_2prim_2poisson__lpmf_8hpp.html',1,'(Global Namespace)'],['../d0/deb/prim_2prob_2poisson__lpmf_8hpp.html',1,'(Global Namespace)']]],
  ['poisson_5frng_2ehpp_7240',['poisson_rng.hpp',['../d8/dac/poisson__rng_8hpp.html',1,'']]],
  ['polar_2ehpp_7241',['polar.hpp',['../d2/da4/fwd_2fun_2polar_8hpp.html',1,'(Global Namespace)'],['../d0/df0/prim_2fun_2polar_8hpp.html',1,'(Global Namespace)'],['../d2/d75/rev_2fun_2polar_8hpp.html',1,'(Global Namespace)']]],
  ['positive_5fconstrain_2ehpp_7242',['positive_constrain.hpp',['../d0/d29/positive__constrain_8hpp.html',1,'']]],
  ['positive_5ffree_2ehpp_7243',['positive_free.hpp',['../da/de0/positive__free_8hpp.html',1,'']]],
  ['positive_5fordered_5fconstrain_2ehpp_7244',['positive_ordered_constrain.hpp',['../db/d1d/prim_2fun_2positive__ordered__constrain_8hpp.html',1,'(Global Namespace)'],['../dd/d45/rev_2fun_2positive__ordered__constrain_8hpp.html',1,'(Global Namespace)']]],
  ['positive_5fordered_5ffree_2ehpp_7245',['positive_ordered_free.hpp',['../de/d73/positive__ordered__free_8hpp.html',1,'']]],
  ['possibly_5fsum_2ehpp_7246',['possibly_sum.hpp',['../da/de3/possibly__sum_8hpp.html',1,'']]],
  ['pow_2ehpp_7247',['pow.hpp',['../d6/dd8/fwd_2fun_2pow_8hpp.html',1,'(Global Namespace)'],['../dc/d79/opencl_2rev_2pow_8hpp.html',1,'(Global Namespace)'],['../d6/dee/prim_2fun_2pow_8hpp.html',1,'(Global Namespace)'],['../d7/df3/rev_2fun_2pow_8hpp.html',1,'(Global Namespace)']]],
  ['precomp_5fvv_5fvari_2ehpp_7248',['precomp_vv_vari.hpp',['../dc/d8d/precomp__vv__vari_8hpp.html',1,'']]],
  ['precomp_5fvvv_5fvari_2ehpp_7249',['precomp_vvv_vari.hpp',['../d8/d0f/precomp__vvv__vari_8hpp.html',1,'']]],
  ['precomputed_5fgradients_2ehpp_7250',['precomputed_gradients.hpp',['../db/d58/precomputed__gradients_8hpp.html',1,'']]],
  ['prim_2ehpp_7251',['prim.hpp',['../d6/dc6/opencl_2prim_8hpp.html',1,'(Global Namespace)'],['../dc/d26/prim_8hpp.html',1,'(Global Namespace)']]],
  ['primitive_5fvalue_2ehpp_7252',['primitive_value.hpp',['../d4/ded/fwd_2fun_2primitive__value_8hpp.html',1,'(Global Namespace)'],['../db/d6b/prim_2fun_2primitive__value_8hpp.html',1,'(Global Namespace)'],['../da/d55/rev_2fun_2primitive__value_8hpp.html',1,'(Global Namespace)']]],
  ['print_5fstack_2ehpp_7253',['print_stack.hpp',['../d9/d8a/print__stack_8hpp.html',1,'']]],
  ['prob_2ehpp_7254',['prob.hpp',['../d9/dfc/fwd_2prob_8hpp.html',1,'(Global Namespace)'],['../db/d59/prim_2prob_8hpp.html',1,'(Global Namespace)'],['../d9/d4c/rev_2prob_8hpp.html',1,'(Global Namespace)']]],
  ['prob_5fconstrain_2ehpp_7255',['prob_constrain.hpp',['../d3/d69/prob__constrain_8hpp.html',1,'']]],
  ['prob_5ffree_2ehpp_7256',['prob_free.hpp',['../d4/d5a/prob__free_8hpp.html',1,'']]],
  ['prod_2ehpp_7257',['prod.hpp',['../da/dd1/opencl_2prim_2prod_8hpp.html',1,'(Global Namespace)'],['../db/d1b/opencl_2rev_2prod_8hpp.html',1,'(Global Namespace)'],['../df/d85/prim_2fun_2prod_8hpp.html',1,'(Global Namespace)']]],
  ['profiling_2ehpp_7258',['profiling.hpp',['../d2/de4/profiling_8hpp.html',1,'']]],
  ['proj_2ehpp_7259',['proj.hpp',['../d3/db1/fwd_2fun_2proj_8hpp.html',1,'(Global Namespace)'],['../d8/d5c/prim_2fun_2proj_8hpp.html',1,'(Global Namespace)'],['../de/de5/rev_2fun_2proj_8hpp.html',1,'(Global Namespace)']]],
  ['promote_5fargs_2ehpp_7260',['promote_args.hpp',['../de/d54/promote__args_8hpp.html',1,'']]],
  ['promote_5felements_2ehpp_7261',['promote_elements.hpp',['../d8/d29/promote__elements_8hpp.html',1,'']]],
  ['promote_5fscalar_2ehpp_7262',['promote_scalar.hpp',['../d9/dfe/promote__scalar_8hpp.html',1,'']]],
  ['promote_5fscalar_5ftype_2ehpp_7263',['promote_scalar_type.hpp',['../d6/d79/promote__scalar__type_8hpp.html',1,'']]],
  ['promote_5fvar_5fmatrix_2ehpp_7264',['promote_var_matrix.hpp',['../d2/d46/promote__var__matrix_8hpp.html',1,'']]],
  ['pseudo_5feigenvalues_2ehpp_7265',['pseudo_eigenvalues.hpp',['../db/deb/pseudo__eigenvalues_8hpp.html',1,'']]],
  ['pseudo_5feigenvectors_2ehpp_7266',['pseudo_eigenvectors.hpp',['../dc/dff/pseudo__eigenvectors_8hpp.html',1,'']]]
];
